name: bump-semver
description: 'Bumps the version number based on input'
author: aboutandre
branding:
  icon: 'archive'
  color: 'green'
inputs:
  file-path:
    description: "Path to pubspec.yaml. Default is ./pubspec.yaml"
    required: false
    default: "./pubspec.yaml"
  bump-type:
    description: "Either PATCH, MINOR or MAJOR"
    required: true
outputs:
  version-number:
    description: "New version with build number"
    value: ${{ steps.bump.outputs.bumped-version }}
runs:
  using: "composite"
  steps:
    - id: bump
      run: |
        VERSION=`cat ${{inputs.file-path}} | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs`
        BUMP_TYPE=${{inputs.bump-type}}
        
        semVersion=`echo $VERSION | sed 's|.*\:||' | sed 's|\(.*\)+.*|\1|' | xargs`
        IFS=. read -r version minor patch <<EOF
        $semVersion
        EOF
        
        case ${BUMP_TYPE^^} in
          PATCH) BUMPED_VERSION="$version.$minor.$((patch+1))"; ;;
          MAJOR) BUMPED_VERSION="$((version+1)).0.0"; ;;
          *)     BUMPED_VERSION="$version.$((minor+1)).0"; ;;
        esac
          
        BUILD_NUMBER=`echo $VERSION | grep -o '+.*' | cut -f2- -d+`
        BUILD_NUMBER=$((BUILD_NUMBER + 1))
        
        echo "::set-output name=bumped-version::$(echo $BUMPED_VERSION+$BUILD_NUMBER)"
      shell: bash
