name: bump-semver
description: 'Bumps the version number based on input'
author: aboutandre
branding:
  icon: 'archive'
  color: 'green'
inputs:
  semver-version:
    description: "A version number following the format MAJOR.MINOR.PATCH"
    required: true
  bump-type:
    description: "Either PATCH, MINOR or MAJOR"
    required: true
outputs:
  version-number:
    description: "New version number"
    value: ${{ steps.bump.outputs.bumped-version }}
runs:
  using: "composite"
  steps:
    - id: bump
      run: |
        BUMP_TYPE=${{inputs.bump-type}}
        
        var=${{inputs.semver-version}}
        IFS=. read -r version minor patch <<EOF
        $var
        EOF
        
        case ${BUMP_TYPE^^} in
          PATCH) tag="$version.$minor.$((patch+1))"; ;;
          MAJOR) tag="$((version+1)).0.0"; ;;
          *)     tag="$version.$((minor+1)).0"; ;;
        esac
          
        
        echo "::set-output name=bumped-version::$(echo tag)"
      shell: bash
