name: branch-exists-guard
description: 'Guard to check if branch exists'
author: aboutandre
branding:
  icon: 'archive'
  color: 'green'
inputs:
  branch:
    description: "The branch ref to check if it exists in the repo"
    required: true
outputs:
  branch-exists:
    description: "The branch exists"
    value: ${{ steps.guard.outputs.branch-exists }}
runs:
  using: "composite"
  steps:
    - id: guard
      run: |
        CHECK=false
        checkForBranch() {
        git ls-remote --exit-code --heads https://github.com/aboutandre/flutter-version-number-action tomato
        CHECK=$?
        }
        checkForBranch
        echo "CHECK"
        echo $CHECK
        BRANCH_EXISTS=$(if [ $CHECK -eq 2 ]; then echo false; else echo true; fi)
        echo "Branch exists"
        echo BRANCH_EXISTS
        echo $BRANCH_EXISTS
        echo "::set-output name=branch-exists::$(echo $BRANCH_EXISTS)"
      shell: bash
