name: branch-exists-guard
description: 'Guard to check if branch exists'
author: aboutandre
branding:
  icon: 'archive'
  color: 'green'
inputs:
  branch:
    description: "The branch ref to check if it exists in the repo"
    required: true
outputs:
  branch-exists:
    description: "The branch exists"
    value: ${{ steps.guard.outputs.branch-exists }}
runs:
  using: "composite"
  steps:
    - id: guard
      run: |
         git branch 
         echo $?
#        echo "This is the exit code"
#        echo $?
#        BRANCH_EXISTS=$(if [ $? -ne 0 ]; then echo true; else echo false; fi)
#        echo "Branch exists"
#        echo BRANCH_EXISTS
#        echo $BRANCH_EXISTS
#        BRANCH_EXISTS=$(git show-branch ${{ inputs.branch }} &>/dev/null && echo true || echo false)
         git show-branch ${{ inputs.branch }} &>/dev/null && echo true || echo false
        echo "::set-output name=branch-exists::$(echo false)"
      shell: bash
