name: branch-exists-guard
description: 'Guard to check if branch exists'
author: aboutandre
branding:
  icon: 'archive'
  color: 'green'
inputs:
  branch:
    description: "The branch ref to check if it exists in the repo"
    required: true
outputs:
  branch-exists:
    description: "The branch exists"
    value: ${{ steps.guard.outputs.branch-exists }}
runs:
  using: "composite"
  steps:
    - id: guard
      run: |
        BRANCH_EXISTS=false
        git ls-remote --exit-code --heads git@github.com:${{ github.repository }} ${{ inputs.branch }}
        if [ $? -eq 2 ]
        then
        BRANCH_EXISTS=false
        else
        BRANCH_EXISTS=true
        fi
        echo "::set-output name=branch-exists::$(echo $BRANCH_EXISTS)"
      shell: bash
