on:
  workflow_dispatch:
    inputs:
      semVer:
        type: choice
        description: Changes level
        required: true
        options:
          - PATCH
          - MINOR
          - MAJOR

name: Checkout test
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Test echo
        run: | 
          echo "Release candidate with level: "${{ github.event.inputs.semVer }}" will be created"
      - uses: actions/checkout@v2
      - name: Bump the version and build number
        id: bump-version
        uses: ./.github/actions/bump-semver
        with:
          bump-type: ${{ github.event.inputs.semVer }}
      - name: Test echo 3
        run: |
          echo "Bumped version number is: ${{steps.bump-version.outputs.steps.bump-version.outputs.bumped-version-number}}"

#      - name: Check that branch does not exist
#        id: check-if-branch-exists
#        uses: ./.github/actions/branch-exists-guard
#        with:
#          branch: 'rc-${{steps.bump-version.outputs.version-number}}'
#      - run: |
#          echo ${{ steps.check-if-branch-exists.outputs.branch-exists }} == 'yes'
#      - name: Check that branch does not exist
#        if: ${{ steps.check-if-branch-exists.outputs.branch-exists }} == 'yes'
#        uses: actions/github-script@v3
#        with:
#          script: |
#              core.setFailed('Branch already exists')
      ### WIP
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'rc-${{steps.bump-version.outputs.bumped-version-number}}'
      - uses: actions/checkout@v2
        with:
          ref: 'rc-${{steps.bump-version.outputs.bumped-version-number}}'
      - name: Update pubspec.yaml version and build number
        run: sed -i -e '1,/${{ steps.bump-version.outputs.parsed-version-number }}/{s/${{ steps.bump-version.outputs.parsed-version-number }}/${{steps.bump-version.outputs.bumped-version-number}}/;}' pubspec.yaml
      - name: Commit and push updated pubspec.yaml
        uses: EndBug/add-and-commit@v8.0.1
        with:
          add: pubspec.yaml
          push: true
          default_author: github_actor
