on:
  workflow_dispatch:
    inputs:
      semVer:
        type: choice
        description: Changes level
        required: true
        options:
          - PATCH
          - MINOR
          - MAJOR
      skip-jira-automation:
        type: boolean
        required: false
        description: "Don't move tickets to TEST"

name: Checkout test
jobs:
  create-release-candidate-branch:
    name: Create Release Candidate Branch
    runs-on: ubuntu-latest
    steps:
      - name: Log RC level chosen
        run: |
          echo "Release candidate with level: "${{ github.event.inputs.sem-ver }}" will be created"
      - uses: actions/checkout@v3
      - name: Bump the version and build number
        id: bump-version
        uses: ./.github/actions/bump-semver
        with:
          bump-type: ${{ github.event.inputs.sem-ver }}
      - uses: peterjgrainger/action-create-branch@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/v${{steps.bump-version.outputs.bumped-version-number}}'
      - uses: actions/checkout@v3
        with:
          ref: 'release/v${{steps.bump-version.outputs.bumped-version-number}}'
      - name: Update pubspec.yaml version and build number
        run: sed -i -e '1,/${{ steps.bump-version.outputs.parsed-version-number }}/{s/${{ steps.bump-version.outputs.parsed-version-number }}/${{steps.bump-version.outputs.bumped-version-number}}/;}' pubspec.yaml
      - name: Commit and push updated pubspec.yaml
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: pubspec.yaml
          push: true
          default_author: github_actor
          message: 'chore: bump version to ${{ steps.bump-version.outputs.bumped-version-number }}'
          tag: '${{ steps.bump-version.outputs.bumped-version-number }}'
          tag_push: '--force'
      - name: Git push changes
        run: git push
      - name: Checkout branch
        run: git checkout release/v${{steps.bump-version.outputs.bumped-version-number}}
    outputs:
      fix-version: ${{ steps.bump-version.outputs.bumped-version-number }}
  choice-check:
    name: "Transition all master tickets to test"
    if: github.event.inputs.skip-jira-automation != true
    needs: [create-release-candidate-branch]
    runs-on: ubuntu-latest
    steps:
      - name: Choice check echo
        run: |
          echo "github.event.inputs.skip-jira-automation: ${{ github.event.inputs.skip-jira-automation }}"
