on:
  workflow_dispatch:
    inputs:
      semVer:
        type: choice
        description: Changes level
        required: true
        options:
          - PATCH
          - MINOR
          - MAJOR

name: Checkout test
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Test echo
        run: | 
          echo "Release candidate with level: "${{ github.event.inputs.semVer }}" will be created"
      - uses: actions/checkout@v2
      - name: Get current pub spec
        id: pubspec-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
#      - name: Get next version without build
#        id: version-without-build-number
#        uses: ./.github/actions/version-without-build-number
#        with:
#          flutter-version: ${{ steps.pubspec-version.outputs.version-number }}
#      - name: Test echo 2
#        run: |
#          echo "Pure version number is: ${{steps.version-without-build-number.outputs.version-number}}"
      - name: Bump the version and build number
        id: bump-version
        uses: ./.github/actions/bump-semver
        with:
          pubspec-version-with-build: ${{ steps.pubspec-version.outputs.version-number }}
          bump-type: ${{ github.event.inputs.semVer }}
      - name: Test echo 3
        run: |
          echo "Bumped version number is: ${{steps.bump-version.outputs.version-number}}"

      - name: Check that branch does not exist
        uses: actions/github-script@v3
        with:
          script: |
            git show-ref --quiet rc-${{steps.bump-version.outputs.version-number}}; then
              core.setFailed('Branch already exists')
            fi
      ### WIP
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'rc-${{steps.bump-version.outputs.version-number}}'
      - uses: actions/checkout@v2
        with:
          ref: 'rc-${{steps.bump-version.outputs.version-number}}'
      - name: Update pubspec.yaml version and build number
        run: sed -i -e 's/${{ steps.pubspec-version.outputs.version-number }}/${{steps.bump-version.outputs.version-number}}/gi' pubspec.yaml
#      - uses: DamianReeves/write-file-action@v1.0
#        with:
#            # The path to the file to write
#          path: ${{ github.workspace }}/tomato.txt
#          contents: |
#            echo "Hello World!"
#          write-mode: overwrite
      - name: Commit and push updated pubspec.yaml
        uses: EndBug/add-and-commit@v8.0.1
        with:
          add: pubspec.yaml
          push: true
          default_author: github_actor
#      - run: git status
#      - run: git config --local user.email "action@github.com"
#      - run: git config --local user.name "GitHub Action"
#      - run: git status
#      - run: git log
#      - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
