on:
  workflow_dispatch:
#     inputs:
#       choice:
#         type: choice
#         description: Make a choice
#         required: true
#         options:
#           - foo
#           - bar
#           - baz

name: Test
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with:
          file-path: example/pubspec.yaml
      - uses: actions/branch@v1
        with:
          branch: 'rc-${{ steps.read-version.outputs.version-number }}'
