# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Create Release Candidate v2"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      sem-ver:
        type: choice
        description: Changes level
        required: true
        options:
          - PATCH
          - MINOR
          - MAJOR
      skip-jira-automation:
        type: boolean
        required: false
        description: "Don't move tickets to TEST"

env:
  node-version: 16.14
  java-distribution: zulu
  java-version: 12
  flutter-version: 2.10.3

#####################################################################################
### ATTENTION: Make sure to test the release with all checks we also use for PRs! ###
#####################################################################################
jobs:
  logs-build-selection:
    name: Logs the selection for the current build
    runs-on: ubuntu-latest
    steps:
      - name: Log RC level chosen
        run: |
          echo "Release candidate with level: "${{ github.event.inputs.sem-ver }}" will be created"
      - name: Log JIRA automation selection
        run: |
          echo "Should move ticket to TEST: "${{ github.event.inputs.skip-jira-automation }}""


  bump-version:
    name: Bump the pubspec version of base branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump the version and build number
        id: bump-version
        uses: ./.github/actions/bump-semver
        with:
          bump-type: ${{ github.event.inputs.sem-ver }}
      - name: Log bumped values
        run: |
          echo "bumped-version-number: "${{ steps.bump-version.outputs.bumped-version-number }}""
          echo "parsed-version-number: "${{ steps.bump-version.outputs.parsed-version-number }}""
    outputs:
      bumped-version-number: ${{ steps.bump-version.outputs.bumped-version-number }}
      parsed-version-number: ${{ steps.bump-version.outputs.parsed-version-number }}



  check-if-tag-exists:
    name: Guard to check if the cadidate tag already exists
    needs: [bump-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history for all branches and tags
          ref: ${{ needs.create-release-candidate-branch.outputs.fix-version }}
      - name: Check input
        run: |
          echo "bumped-version-number ${{ needs.bump-version.outputs.bumped-version-number }}"
      - name: Check if tag already exists
        id: tag-guard
        uses: ./.github/actions/tag-exists-guard
        with:
          tag: ${{ needs.bump-version.outputs.bumped-version-number }}
    outputs:
      tagExists: ${{ steps.tag-guard.outputs.tag-exists }}

  create-release-candidate-branch:
    name: Create Release Candidate Branch
    needs: [ check-if-tag-exists, bump-version ]
    if: needs.check-if-tag-exists.outputs.tagExists == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag exists
        run: |
          echo "needs.check-if-tag-exists.outputs.tagExists: ${{ needs.check-if-tag-exists.outputs.tagExists }}"
      - uses: actions/checkout@v3
      - uses: peterjgrainger/action-create-branch@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'v${{needs.bump-version.outputs.bumped-version-number}}'
      - uses: actions/checkout@v3
        with:
          ref: 'v${{needs.bump-version.outputs.bumped-version-number}}'
      - name: Update pubspec.yaml version and build number
        run: sed -i -e '1,/${{ needs.bump-version.outputs.parsed-version-number }}/{s/${{ needs.bump-version.outputs.parsed-version-number }}/${{needs.bump-version.outputs.bumped-version-number}}/;}' pubspec.yaml
      - name: Commit and push updated pubspec.yaml
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: pubspec.yaml
          push: true
          default_author: github_actor
          message: 'chore: bump version to ${{ needs.bump-version.outputs.bumped-version-number }}'
          tag: '${{ needs.bump-version.outputs.bumped-version-number }}'
          tag_push: '--force'
      - name: Git push changes
        run: git push
      - name: Checkout branch
        run: git checkout v${{needs.bump-version.outputs.bumped-version-number}}
    outputs:
      fix-version: ${{ needs.bump-version.outputs.bumped-version-number }}

  transition-jira-tickets:
    if: github.event.inputs.skip-jira-automation != 'true'
    name: "Transition all master tickets to test"
    runs-on: ubuntu-latest
    needs: [ create-release-candidate-branch ]
    steps:
      - name: Create release from current pubspec and edit tickets accordingly
        run: |
          echo "I would transition all master tickets to test"

  test-dependency:
    name: Just a job to test if create-release-candidate-branch triggers this job
    needs: [create-release-candidate-branch]
    runs-on: ubuntu-latest
    steps:
      - name: Simple logging
        run: |
          echo "I am dependent on create-release-candidate-branch"

  create-pr-into-master: # because master is protected we use a pull request to bypass this restriction in automation
    name: "Create PR for branch merge back into master"
    runs-on: ubuntu-latest
    needs: [ create-release-candidate-branch, test-dependency ]
    steps:
      - uses: actions/checkout@v3 # we need to do a checkout before pr creation
        with:
          fetch-depth: 0 # fetch all history for all branches and tags for release notes
          ref: 'v${{ needs.create-release-candidate-branch.outputs.fix-version }}'
      - name: pull-request
        uses: repo-sync/pull-request@v2
        id: open-pr
        with:
          source_branch: 'v${{ needs.create-release-candidate-branch.outputs.fix-version }}'
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "[GithubActions] Release v${{ needs.create-release-candidate-branch.outputs.fix-version }}"
      - name: output-number
        run: echo ${{steps.open-pr.outputs.pr_number}}
    outputs:
      pr-number: ${steps.open-pr.outputs.pr_number}

  merge-release-into-master:
    name: "Merge release branch back into master"
    runs-on: ubuntu-latest
    needs: [ create-release-candidate-branch, create-pr-into-master ]
    steps:
      - name: "Find Pull Request"
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'v${{ needs.create-release-candidate-branch.outputs.fix-version }}'
      - run: echo "Pull Request ${number} (${sha})"
        env:
          number: ${{ steps.find-pull-request.outputs.number }}
          sha: ${{ steps.find-pull-request.outputs.head-sha }}
      - name: "Merge pull request"
        uses: "actions/github-script@v6"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repository = context.repo
            await github.rest.pulls.merge({
              merge_method: "merge",
              owner: repository.owner,
              pull_number: ${{ steps.find-pull-request.outputs.number }},
              repo: repository.repo,
            })
