# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Create Release Candidate v2"

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      sem-ver:
        type: choice
        description: Changes level
        required: true
        options:
          - PATCH
          - MINOR
          - MAJOR
      skip-jira-automation:
        type: boolean
        required: false
        description: "Don't move tickets to TEST"

env:
  node-version: 16.14
  java-distribution: zulu
  java-version: 12
  flutter-version: 2.10.3

#####################################################################################
### ATTENTION: Make sure to test the release with all checks we also use for PRs! ###
#####################################################################################
jobs:
  logs-build-selection:
    name: Logs the selection for the current build
    runs-on: ubuntu-latest
    steps:
      - name: Log RC level chosen
        run: |
          echo "Release candidate with level: "${{ github.event.inputs.sem-ver }}" will be created"
      - name: Log JIRA automation selection
        run: |
          echo "Should move ticket to TEST: "${{ github.event.inputs.skip-jira-automation }}""


  bump-version:
    name: Bump the pubspec version of base branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump the version and build number
        id: bump-version
        uses: ./.github/actions/bump-semver
        with:
          bump-type: ${{ github.event.inputs.sem-ver }}
      - name: Log bumped values
        run: |
          echo "bumped-version-number: "${{ steps.bump-version.outputs.bumped-version-number }}""
          echo "parsed-version-number: "${{ steps.bump-version.outputs.parsed-version-number }}""
    outputs:
      bumped-version-number: ${{ steps.bump-version.outputs.bumped-version-number }}
      parsed-version-number: ${{ steps.bump-version.outputs.parsed-version-number }}



  check-if-tag-exists:
    name: Guard to check if the cadidate tag already exists
    needs: [bump-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check input
        run: |
          echo "bumped-version-number ${{ needs.bump-version.outputs.bumped-version-number }}"
    outputs:
      tagIsNew: git rev-parse "refs/tags/${{ needs.bump-version.outputs.bumped-version-number }}" >/dev/null 2>&1

  create-release-candidate-branch:
    name: Create Release Candidate Branch
    needs: [ check-if-tag-exists, bump-version ]
    if: needs.check-if-tag-exists.outputs.tagIsNew
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag exists
        run: |
          echo "needs.check-if-tag-exists.outputs.tagIsNew: ${{ needs.check-if-tag-exists.outputs.tagIsNew }}"
      - uses: actions/checkout@v3
      - uses: peterjgrainger/action-create-branch@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'v${{needs.bump-version.outputs.bumped-version-number}}'
      - uses: actions/checkout@v3
        with:
          ref: 'v${{needs.bump-version.outputs.bumped-version-number}}'
      - name: Update pubspec.yaml version and build number
        run: sed -i -e '1,/${{ needs.bump-version.outputs.parsed-version-number }}/{s/${{ needs.bump-version.outputs.parsed-version-number }}/${{needs.bump-version.outputs.bumped-version-number}}/;}' pubspec.yaml
      - name: Commit and push updated pubspec.yaml
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: pubspec.yaml
          push: true
          default_author: github_actor
          message: 'chore: bump version to ${{ needs.bump-version.outputs.bumped-version-number }}'
          tag: '${{ needs.bump-version.outputs.bumped-version-number }}'
          tag_push: '--force'
      - name: Git push changes
        run: git push
      - name: Checkout branch
        run: git checkout v${{needs.bump-version.outputs.bumped-version-number}}
    outputs:
      fix-version: ${{ needs.bump-version.outputs.bumped-version-number }}
